name: Compile Geth

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go environment
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'  # Specify the Go version you want to use

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgmp-dev libssl-dev

    - name: Download go-ethereum repository (single branch)
      run: |
        git clone --single-branch --branch master https://github.com/ethereum/go-ethereum.git
        cd go-ethereum

    - name: Record compilation time
      run: |
        START_TIME=$(date +%s)
        cd go-ethereum
        make geth
        END_TIME=$(date +%s)
        COMPILATION_TIME=$((END_TIME - START_TIME))
        echo "Compilation time: $COMPILATION_TIME seconds"
