name: Pull Request Event

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_1"
      - name: sleep1
        run: sleep 10800

  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_1"
      - name: sleep2
        run: sleep 10800

  job_3:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_1"
      - name: sleep3
        run: sleep 10800
        
  
  run-client-pr:
    runs-on: ubuntu-latest
    environment: test
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: test key1
      run: echo "999"

    - name: run test key2
      run: echo "888"
      # run: echo "SERVER_TEST="

    - name: Print environment variables
      env:
          SERVER_TEST: ${{ secrets.TEST_KEY }}
      run: echo "SERVER_TEST=$TEST_KEY"
    
    - name: Run client_pull_request script
      run: python3 client.py "${{ secrets.SERVER_IP }}" ${{ secrets.SERVER_PORT }} "pull action" ${{ secrets.TEST_KEY }}

    
